### get all workouts from a user
GET http://127.0.0.1:3000/api/v1/workouts/1

### get user by ID
GET http://127.0.0.1:3000/api/v1/users/1

### get all users
GET http://127.0.0.1:3000/api/v1/users

### follow a user
PATCH http://127.0.0.1:3000/api/v1/users/follow/1/2

### unfollow a user
PATCH http://127.0.0.1:3000/api/v1/users/unfollow/1/2

### remove a workout from a user
DELETE http://127.0.0.1:3000/api/v1/workouts/1/3

### get a uid by username
GET http://127.0.0.1:3000/api/v1/users/username/a

### get list of users a user is following
GET http://127.0.0.1:3000/api/v1/users/following/1