### get all workouts from a user
GET http://127.0.0.1:3000/api/v1/workouts/a

### get user by username
GET http://127.0.0.1:3000/api/v1/users/a

### get all users
GET http://127.0.0.1:3000/api/v1/users

### follow a user
PATCH http://127.0.0.1:3000/api/v1/users/follow/a/b

### unfollow a user
PATCH http://127.0.0.1:3000/api/v1/users/unfollow/a/b

### remove a workout from a user
DELETE http://127.0.0.1:3000/api/v1/workouts/a/1


### get list of users a user is following
GET http://127.0.0.1:3000/api/v1/users/following/a

### remove user
DELETE http://127.0.0.1:3000/api/v1/users/b

### login
POST http://127.0.0.1:3000/api/v1/users/login
Content-Type: application/json

{
    "username": "a",
    "password": "a"
}

